// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'camera.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `run_coordinator`, `send`, `session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Discovers and connects to a camera on `port`, replaying the same
/// probe-then-reconnect sequence `main.rs` uses (discovery's own connection
/// only lives for the duration of the probe, so a second connection is
/// opened for the worker thread to hold onto), then starts that camera's
/// worker and debounce-coordinator threads.
///
/// Replaces any previously active session.
Future<ConnectedInfo> connect({required String port}) =>
    RustLib.instance.api.crateApiCameraConnect(port: port);

/// Streams status updates for the active session to `sink` until the
/// worker thread goes away. Only one subscriber is ever served per
/// [`connect`] call — a second call while one is already streaming returns
/// immediately with no events, since a `Receiver` can't be split between
/// two consumers; the Flutter side should subscribe once (e.g. behind a
/// single `asBroadcastStream()`) rather than per-widget.
Stream<StatusEvent> subscribeStatus() =>
    RustLib.instance.api.crateApiCameraSubscribeStatus();

/// Sends a single pan/tilt nudge in `direction`, `degrees` wide — the
/// caller (the joystick widget) is expected to derive `degrees` from how
/// far the drag is from center, same idea as the D70 Commander's jog area.
Future<void> nudgePanTilt({
  required Direction8 direction,
  required double degrees,
}) => RustLib.instance.api.crateApiCameraNudgePanTilt(
  direction: direction,
  degrees: degrees,
);

Future<void> nudgeZoomIn({required BigInt millis}) =>
    RustLib.instance.api.crateApiCameraNudgeZoomIn(millis: millis);

Future<void> nudgeZoomOut({required BigInt millis}) =>
    RustLib.instance.api.crateApiCameraNudgeZoomOut(millis: millis);

Future<void> nudgeFocusNear({required BigInt millis}) =>
    RustLib.instance.api.crateApiCameraNudgeFocusNear(millis: millis);

Future<void> nudgeFocusFar({required BigInt millis}) =>
    RustLib.instance.api.crateApiCameraNudgeFocusFar(millis: millis);

Future<void> recallPreset({required int number}) =>
    RustLib.instance.api.crateApiCameraRecallPreset(number: number);

Future<void> savePreset({required int number}) =>
    RustLib.instance.api.crateApiCameraSavePreset(number: number);

/// A snapshot of the camera's pan/tilt/zoom/focus/power state, mirroring
/// [`viscous::state::CameraState`] with only bridge-safe field types.
class CameraState {
  final bool powerOn;
  final int pan;
  final int tilt;
  final int zoom;
  final int focus;

  const CameraState({
    required this.powerOn,
    required this.pan,
    required this.tilt,
    required this.zoom,
    required this.focus,
  });

  @override
  int get hashCode =>
      powerOn.hashCode ^
      pan.hashCode ^
      tilt.hashCode ^
      zoom.hashCode ^
      focus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraState &&
          runtimeType == other.runtimeType &&
          powerOn == other.powerOn &&
          pan == other.pan &&
          tilt == other.tilt &&
          zoom == other.zoom &&
          focus == other.focus;
}

/// What a successful connection attempt found, mirroring the summary
/// `main.rs` builds from [`viscous::connection::ProbeOutcome`].
class ConnectedInfo {
  final int baudRate;
  final String summary;

  const ConnectedInfo({required this.baudRate, required this.summary});

  @override
  int get hashCode => baudRate.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectedInfo &&
          runtimeType == other.runtimeType &&
          baudRate == other.baudRate &&
          summary == other.summary;
}

/// The eight directions a pan/tilt drag can move in, mirroring
/// [`viscous::pan_tilt::NudgeDirection`].
enum Direction8 { up, down, left, right, upLeft, upRight, downLeft, downRight }

@freezed
sealed class StatusEvent with _$StatusEvent {
  const StatusEvent._();

  const factory StatusEvent.state(CameraState field0) = StatusEvent_State;
  const factory StatusEvent.command(String field0) = StatusEvent_Command;
}
